inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.3

  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

  DisplayCopNames: true

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*rb'
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
